/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OrdenarMedicam;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author user
 */
public class OpcionesPedido extends javax.swing.JFrame implements ActionListener {
    private final PedidoManager pedidoManager;
    /**
     * Creates new form OpcionesPedido
     */
    public OpcionesPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        pedidoManager = new PedidoManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtNombMedicam = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblSaludo = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        lblBench = new javax.swing.JLabel();
        lblNombMedicam = new javax.swing.JLabel();
        cbTipoMedic = new javax.swing.JComboBox<>();
        lblTipoMedicam1 = new javax.swing.JLabel();
        txtCantidadMedic = new javax.swing.JTextField();
        lblCantidadMedicam1 = new javax.swing.JLabel();
        rbDist3 = new javax.swing.JRadioButton();
        rbDist1 = new javax.swing.JRadioButton();
        rbDist2 = new javax.swing.JRadioButton();
        lblDistribuidor1 = new javax.swing.JLabel();
        cbPrincip = new javax.swing.JCheckBox();
        cbSecund = new javax.swing.JCheckBox();
        btnConfirmar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblGracias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedido en línea");
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombMedicam.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        txtNombMedicam.setToolTipText("Digita el nombre del medicamento y su presentación");
        bg.add(txtNombMedicam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 320, 30));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_Drogueria_circ_p.png"))); // NOI18N
        bg.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 160, 150));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setBackground(new java.awt.Color(0, 51, 102));
        lblNombre.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 51, 102));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("FARMAVIDA");
        lblNombre.setAlignmentY(0.8F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 230, 40));

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tabletas.png"))); // NOI18N
        lblPhoto.setText("jLabel1");
        bg.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 230, 530));

        lblSaludo.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        lblSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludo.setText("Haz tu pedido en línea de forma fácil y segura");
        lblSaludo.setToolTipText("");
        bg.add(lblSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 480, 50));

        lblInstrucciones.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lblInstrucciones.setText("Por favor, diligencia todos los campos.");
        bg.add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 30));

        lblBench.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblBench.setText("Selecciona la sucursal");
        bg.add(lblBench, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 220, 30));

        lblNombMedicam.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblNombMedicam.setText("Nombre del medicamento");
        bg.add(lblNombMedicam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, 30));

        cbTipoMedic.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        cbTipoMedic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibiótico" }));
        cbTipoMedic.setToolTipText("Seleccionar tipo medicamento");
        bg.add(cbTipoMedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 320, 30));

        lblTipoMedicam1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblTipoMedicam1.setText("Tipo de medicamento");
        bg.add(lblTipoMedicam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 30));

        txtCantidadMedic.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        txtCantidadMedic.setToolTipText("Se digita la cantidad de medicamento requerida");
        bg.add(txtCantidadMedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 320, 30));

        lblCantidadMedicam1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblCantidadMedicam1.setText("Cantidad de medicamento");
        bg.add(lblCantidadMedicam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 220, 30));

        rbDist3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        rbDist3.setText("Cemefar");
        bg.add(rbDist3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        rbDist1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        rbDist1.setText("Cofarma");
        bg.add(rbDist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        rbDist2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        rbDist2.setText("Empsephar");
        bg.add(rbDist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblDistribuidor1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        lblDistribuidor1.setText("Selecciona el distribuidor");
        bg.add(lblDistribuidor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 220, 30));

        cbPrincip.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        cbPrincip.setText("Principal");
        bg.add(cbPrincip, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        cbSecund.setText("Secundaria");
        bg.add(cbSecund, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        btnConfirmar.setBackground(new java.awt.Color(0, 153, 51));
        btnConfirmar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        bg.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 260, 50));

        btnBorrar.setText("Borrar");
        bg.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 100, 30));

        lblGracias.setFont(new java.awt.Font("Franklin Gothic Book", 3, 18)); // NOI18N
        lblGracias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGracias.setText("¡Gracias por preferirnos!");
        bg.add(lblGracias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 490, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupListeners() {
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
    }
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
        // Capturar datos del formulario
        pedidoManager.setNombreMedicamento(txtNombMedicam.getText());
        pedidoManager.setTipoMedicamento(cbTipoMedic.getSelectedItem().toString());
        pedidoManager.setCantidadMedicamento(Integer.parseInt(txtCantidadMedic.getText()));

        if (rbDist1.isSelected()) {
            pedidoManager.setDistribuidor(rbDist1.getText());
        } else if (rbDist2.isSelected()) {
            pedidoManager.setDistribuidor(rbDist2.getText());
        } else if (rbDist3.isSelected()) {
            pedidoManager.setDistribuidor(rbDist3.getText());
        }

        if (cbPrincip.isSelected()) {
            pedidoManager.setSucursal(cbPrincip.getText());
        } else if (cbSecund.isSelected()) {
            pedidoManager.setSucursal(cbSecund.getText());
        }

        // Pasar los datos a ResumenPedido
        ResumenPedido resumenPedido = new ResumenPedido(pedidoManager);
        resumenPedido.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesPedido().setVisible(true);
            }
        });
    }  
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox cbPrincip;
    private javax.swing.JCheckBox cbSecund;
    private javax.swing.JComboBox<String> cbTipoMedic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBench;
    private javax.swing.JLabel lblCantidadMedicam1;
    private javax.swing.JLabel lblDistribuidor1;
    private javax.swing.JLabel lblGracias;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombMedicam;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JLabel lblTipoMedicam1;
    private javax.swing.JRadioButton rbDist1;
    private javax.swing.JRadioButton rbDist2;
    private javax.swing.JRadioButton rbDist3;
    private javax.swing.JTextField txtCantidadMedic;
    private javax.swing.JTextField txtNombMedicam;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
