/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OrdenarMedicam;

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author user
 */
public class ResumenPedido extends javax.swing.JFrame {
    private PedidoManager pedidoManager;
    /**
     * Creates new form ResumenPedido
     * @param pedidoManager
     */
    public ResumenPedido(PedidoManager pedidoManager) {
        this.pedidoManager= pedidoManager;
        initComponents();
        mostrarResumen();
    }

    private ResumenPedido() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlResmnPed = new javax.swing.JPanel();
        lblResmnPed = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        lblXUnddeTM = new javax.swing.JLabel();
        lblDistribuid = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resumen Pedido");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_Drogueria_circ_p.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        pnlResmnPed.setBackground(new java.awt.Color(255, 255, 255));

        lblResmnPed.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        lblResmnPed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResmnPed.setText("Resumen del pedido");

        javax.swing.GroupLayout pnlResmnPedLayout = new javax.swing.GroupLayout(pnlResmnPed);
        pnlResmnPed.setLayout(pnlResmnPedLayout);
        pnlResmnPedLayout.setHorizontalGroup(
            pnlResmnPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResmnPedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblResmnPed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlResmnPedLayout.setVerticalGroup(
            pnlResmnPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResmnPedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblResmnPed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlResmnPed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 30));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CompraMedicam_p.png"))); // NOI18N
        jPanel1.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 170));

        lblXUnddeTM.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lblXUnddeTM.setText("X Unidades del T M");
        jPanel1.add(lblXUnddeTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        lblDistribuid.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lblDistribuid.setText("Pedido al distribuidor");
        jPanel1.add(lblDistribuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblUbicacion.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        lblUbicacion.setText("Para la farmacia situada en D");
        jPanel1.add(lblUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        btnEnviar.setBackground(new java.awt.Color(0, 204, 51));
        btnEnviar.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("ENVIAR");
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupListeners() {
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
    }

    private void mostrarResumen() {
        lblXUnddeTM.setText(pedidoManager.getCantidadMedicamento() + " Unidades de " + pedidoManager.getTipoMedicamento() + " " + pedidoManager.getNombreMedicamento());
        lblDistribuid.setText("Pedido al distribuidor: " + pedidoManager.getDistribuidor());
        lblUbicacion.setText("Para la farmacia situada en " + pedidoManager.getSucursal());
    }

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        // Lógica para enviar el pedido
        JOptionPane.showMessageDialog(this, "Pedido enviado exitosamente!");
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        // Lógica para cancelar el pedido
        this.dispose();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Este constructor no debe ser utilizado directamente
                // porque requiere un PedidoManager
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    
    /**public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumenPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumenPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumenPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumenPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenPedido().setVisible(true);
            }
        });
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDistribuid;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblResmnPed;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblXUnddeTM;
    private javax.swing.JPanel pnlResmnPed;
    // End of variables declaration//GEN-END:variables
}
